name: youtube3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  device_info_plus: ^8.0.0
  drag_and_drop_lists: ^0.3.2+2
  #  fab_circular_menu:
  fab_circular_menu_plus: ^0.0.2
  flutter:
    sdk: flutter

  flutter_launcher_icons:
  flutter_native_splash:
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/playbutton.png"
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
